# Generated by Django 4.2.6 on 2023-10-10 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='first_name',
            new_name='first_name_1',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='last_name',
            new_name='last_name_1',
        ),
    ]
