# Generated by Django 4.2.6 on 2023-10-10 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_first_name_profile_first_name_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='first_name_1',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='last_name_1',
            new_name='last_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
