# Generated by Django 4.2.6 on 2023-10-09 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.exchange')),
            ],
        ),
        migrations.CreateModel(
            name='Sentiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateField()),
                ('title', models.CharField(max_length=200)),
                ('negative', models.DecimalField(decimal_places=3, max_digits=4)),
                ('neutral', models.DecimalField(decimal_places=3, max_digits=4)),
                ('positive', models.DecimalField(decimal_places=3, max_digits=4)),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.ticker')),
            ],
        ),
    ]
